/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "tertiary-container": "#adabab",
          "on-primary-container": "#503d00",
          "outline": "#99907e",
          "surface-container-high": "#292a27",
          "surface-container-highest": "#333532",
          "error": "#ffb4ab",
          "surface-container-low": "#1a1c19",
          "inverse-on-surface": "#2f312e",
          "surface-variant": "#333532",
          "primary-fixed-dim": "#e6c364",
          "background": "#121411",
          "on-secondary-fixed": "#410003",
          "tertiary-fixed-dim": "#c9c6c5",
          "primary-container": "#c9a84c",
          "secondary-container": "#8e1c1c",
          "on-tertiary-fixed-variant": "#474646",
          "on-tertiary-container": "#403f3f",
          "secondary": "#ffb3ac",
          "secondary-fixed-dim": "#ffb3ac",
          "on-secondary": "#680007",
          "error-container": "#93000a",
          "primary": "#e6c364",
          "on-primary": "#3d2e00",
          "on-tertiary-fixed": "#1c1b1b",
          "primary-fixed": "#ffe08f",
          "on-secondary-fixed-variant": "#8a1a1a",
          "surface-dim": "#121411",
          "on-surface-variant": "#d0c5b2",
          "tertiary-fixed": "#e5e2e1",
          "on-primary-fixed-variant": "#584400",
          "on-secondary-container": "#ff9e96",
          "surface-bright": "#383a36",
          "on-tertiary": "#313030",
          "surface-tint": "#e6c364",
          "on-surface": "#e3e3de",
          "inverse-surface": "#e3e3de",
          "on-error-container": "#ffdad6",
          "surface-container-lowest": "#0d0f0c",
          "secondary-fixed": "#ffdad6",
          "surface-container": "#1e201d",
          "tertiary": "#c9c6c6",
          "on-primary-fixed": "#241a00",
          "surface": "#121411",
          "on-error": "#690005",
          "on-background": "#e3e3de",
          "outline-variant": "#4d4637",
          "inverse-primary": "#755b00"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "gutter": "16px",
          "section-gap-mobile": "48px",
          "container-margin": "24px",
          "base": "8px",
          "section-gap-desktop": "80px"
      },
      "fontFamily": {
          "headline-sm": ["Playfair Display", "serif"],
          "label-md": ["Inter", "sans-serif"],
          "display-lg-mobile": ["Playfair Display", "serif"],
          "display-lg": ["Playfair Display", "serif"],
          "price-md": ["EB Garamond", "serif"],
          "body-md": ["Inter", "sans-serif"],
          "headline-md": ["Playfair Display", "serif"],
          "price-lg": ["EB Garamond", "serif"],
          "body-lg": ["Inter", "sans-serif"]
      },
      "fontSize": {
          "headline-sm": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
          "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}],
          "display-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
          "display-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "price-md": ["20px", {"lineHeight": "1", "fontWeight": "500"}],
          "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
          "price-lg": ["24px", {"lineHeight": "1", "fontWeight": "500"}],
          "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
